package com.satish.urlshortener.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * One row in the url_mapping table.
 * Stores one short code and the original long URL it points to.
 * The table itself is created by Flyway (V1__init.sql).
 */
@Entity
@Table(name = "url_mapping")
public class UrlMapping {

    /** Primary key, generated by MySQL (AUTO_INCREMENT). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The short code, for example "aB3xY9k". Unique in the table. */
    @Column(name = "short_code", nullable = false, length = 16, unique = true)
    private String shortCode;

    /** The original long URL the user gave us. */
    @Column(name = "original_url", nullable = false, length = 2048)
    private String originalUrl;

    /** When this mapping was created. */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /** JPA needs an empty constructor. */
    protected UrlMapping() {
    }

    public UrlMapping(String shortCode, String originalUrl, Instant createdAt) {
        this.shortCode = shortCode;
        this.originalUrl = originalUrl;
        this.createdAt = createdAt;
    }

    public Long getId() {
        return id;
    }

    public String getShortCode() {
        return shortCode;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}