package com.satish.urlshortener.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * One row in the url_mapping table.
 * Stores one short code and the original long URL it points to.
 * The table itself is created by Flyway migrations (V1, V2, V3).
 */
@Entity
@Table(name = "url_mapping")
public class UrlMapping {

    /** Primary key, generated by MySQL (AUTO_INCREMENT). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The short code, for example "aB3xY9k". Unique in the table. */
    @Column(name = "short_code", nullable = false, length = 16, unique = true)
    private String shortCode;

    /** The original long URL the user gave us. */
    @Column(name = "original_url", nullable = false, length = 2048)
    private String originalUrl;

    /** When this mapping was created. */
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    /** When this link stops working. NULL = never expires. */
    @Column(name = "expires_at")
    private Instant expiresAt;

    /** How many times this short link was opened. Starts at 0. */
    @Column(name = "click_count", nullable = false)
    private long clickCount;

    /** When this link was opened last time. NULL = never opened. */
    @Column(name = "last_accessed_at")
    private Instant lastAccessedAt;

    /** JPA needs an empty constructor. */
    protected UrlMapping() {
    }

    public UrlMapping(String shortCode, String originalUrl, Instant createdAt, Instant expiresAt) {
        this.shortCode = shortCode;
        this.originalUrl = originalUrl;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
    }

    public Long getId() {
        return id;
    }

    public String getShortCode() {
        return shortCode;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public long getClickCount() {
        return clickCount;
    }

    public Instant getLastAccessedAt() {
        return lastAccessedAt;
    }

    /** True if this link has an expiry time and that time has passed. */
    public boolean isExpired() {
        return expiresAt != null && Instant.now().isAfter(expiresAt);
    }
}